### ISSUE TITLE
@capacitor/camera@latest cannot be installed with @capacitor/core@latest

### ISSUE THREAD

**Issue by JorisDebonnet** [ionic-team/capacitor-plugins#171]
### Plugin(s)
@capacitor/camera @ 0.1.2

### Capacitor Version
```
   Capacitor Doctor

Latest Dependencies:

  @capacitor/cli: 2.4.5
  @capacitor/core: 2.4.5
  @capacitor/android: 2.4.5
  @capacitor/electron: 2.4.5
  @capacitor/ios: 2.4.5

Installed Dependencies:

  @capacitor/ios not installed
  @capacitor/cli 2.4.5
  @capacitor/android 2.4.5
  @capacitor/core 2.4.5
  @capacitor/electron not installed
```

### Platform(s)
All

### Current Behavior
Build fails. 
```
$ ng build
✔ Browser application bundle generation complete.

Error: node_modules/@capacitor/camera/dist/esm/definitions.d.ts:1:15 - error TS2724: Module '"../../../core/dist/esm"' has no exported member 'PermissionState'. Did you mean 'PermissionType'?

1 import type { PermissionState } from '@capacitor/core';
                ~~~~~~~~~~~~~~~

  node_modules/@capacitor/core/dist/esm/core-plugin-definitions.d.ts:1243:21
    1243 export declare enum PermissionType {
                             ~~~~~~~~~~~~~~
    'PermissionType' is declared here.
```

I notice [there has been a PR](https://github.com/ionic-team/capacitor/pull/3775) to expose PermissionState, but this has only made it into a core@3.0.0-alpha release, not into core@2.x. 

### Expected Behavior
Any plugin@latest should be installable with core@latest. It's in all official docs like this.

Either this plugin's release tag should be made to work with core@2.4.5, or core@2.x needs that same PR released.

**Comment by jcesarmobile** [comment]
@capacitor/camera is not intended to be used with Capacitor 2, if you want to use this plugin (or any other in this repo) you'll have to use capacitor 3.0.0.alpha.

Capacitor 2 still includes the Camera plugin in its core, so you should use the included plugin instead of this one.

**Comment by bhandaribhuminpfizer** [comment]
@jcesarmobile  i have used capacitor @3.0.0-rc.0 but still getting same error 
![Screenshot 2021-04-06 at 8 46 50 PM](https://user-images.githubusercontent.com/79249987/113734882-5ae70c00-9719-11eb-988a-8c308aeec9ae.png)

**Comment by phoenix503** [comment]
I am getting the same issues

```
ERROR in ../node_modules/@capacitor/camera/dist/esm/definitions.d.ts:1:13 - error TS1005: '=' expected.

1 import type { PermissionState } from '@capacitor/core';
              ~
../node_modules/@capacitor/camera/dist/esm/definitions.d.ts:1:38 - error TS1005: ';' expected.

1 import type { PermissionState } from '@capacitor/core';
                                       ~~~~~~~~~~~~~~~~~
../node_modules/@capacitor/camera/dist/esm/index.d.ts:1:13 - error TS1005: '=' expected.

1 import type { CameraPlugin } from './definitions';
              ~
../node_modules/@capacitor/camera/dist/esm/index.d.ts:1:35 - error TS1005: ';' expected.

1 import type { CameraPlugin } from './definitions';
                                    ~~~~~~~~~~~~~~~
../node_modules/@capacitor/device/dist/esm/index.d.ts:1:13 - error TS1005: '=' expected.

1 import type { DevicePlugin } from './definitions';
              ~
../node_modules/@capacitor/device/dist/esm/index.d.ts:1:35 - error TS1005: ';' expected.

1 import type { DevicePlugin } from './definitions';
                                    ~~~~~~~~~~~~~~~
```

my package.json file

```
 "dependencies": {
        "@agm/core": "^1.0.0-beta.7",
        "@angular/animations": "^8.2.1",
        "@angular/cdk": "^8.2.1",
        "@angular/common": "^8.2.1",
        "@angular/compiler": "^8.2.1",
        "@angular/core": "^8.2.1",
        "@angular/forms": "^8.2.1",
        "@angular/material": "^8.1.2",
        "@angular/material-moment-adapter": "^8.1.2",
        "@angular/platform-browser": "^8.2.1",
        "@angular/platform-browser-dynamic": "^8.2.1",
        "@angular/router": "^8.2.1",
        "@capacitor/camera": "^1.0.2",
        "@capacitor/cli": "^3.0.2",
        "@capacitor/core": "^3.0.2",
        "@capacitor/device": "^1.0.2",
        "ng2-charts": "2.3.0",
        "ngx-bootstrap": "^4.3.0",
        "ngx-color-picker": "^8.2.0",
        "ngx-device-detector": "^2.0.10",
        "ngx-ellipsis": "^2.1.2",
        "ngx-infinite-scroll": "^7.2.0",
        "ngx-mapbox-gl": "^4.5.0",
        "ngx-mat-select-search": "1.8.0",
        "ngx-material-timepicker": "^4.0.2",
        "quill": "^1.3.7",
        "rxjs": "~6.4.0",
        "tslib": "^1.9.0",
        "underscore": "^1.9.2",
        "uuid": "^8.3.2",
        "uuid-generator-ts": "^1.0.3",
        "web-animations-js": "^2.3.2",
        "workbox-cli": "^5.1.4",
        "xlsx": "^0.15.4",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular-builders/custom-webpack": "8.4.1",
        "@angular-devkit/build-angular": "^0.803.21",
        "@angular/cli": "^8.3.21",
        "@angular/compiler-cli": "^8.2.1",
        "@angular/language-service": "^8.2.1",
        "@babel/core": "^7.7.7",
        "@types/bootstrap": "^4.3.1",
        "@types/jasmine": "^3.4.0",
        "@types/jasminewd2": "~2.0.3",
        "@types/lodash-es": "^4.17.3",
        "@types/mapbox-gl": "^1.9.1",
        "@types/node": "^8.9.5",
        "@types/uuid": "^8.3.0",
        "@typescript-eslint/eslint-plugin": "^2.19.0",
        "@typescript-eslint/eslint-plugin-tslint": "^2.19.0",
        "@typescript-eslint/parser": "^2.19.0",
        "babel-loader": "^8.0.6",
        "codelyzer": "^5.2.1",
        "eslint": "^6.8.0",
        "eslint-config-airbnb-angular": "^1.0.0",
        "eslint-config-prettier": "^6.10.0",
        "eslint-plugin-import": "^2.20.1",
        "eslint-plugin-prettier": "^3.1.2",
        "jasmine-core": "~3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "^2.1.0",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.5.1",
        "lint-staged": "^10.0.7",
        "prettier": "^1.19.1",
        "pretty-quick": "^2.0.1",
        "ts-node": "~7.0.0",
        "tslint": "~5.15.0",
        "typescript": "~3.4.3"
    },
    "lint-staged": {
        "*.ts": [
            "eslint"
        ]
    }
```

**Comment by davidEcclesEntSys** [comment]
same issue, cap v 3.1.2, TS2304 errors, cannot find permissionState/ cameraPlugin/ from

**Comment by Mirofq** [comment]
Same issue with me. Do you happen to fix this? I am using same dependency as you

**Comment by Mirofq** [comment]
> I am getting the same issues
> 
> ```
> ERROR in ../node_modules/@capacitor/camera/dist/esm/definitions.d.ts:1:13 - error TS1005: '=' expected.
> 
> 1 import type { PermissionState } from '@capacitor/core';
>               ~
> ../node_modules/@capacitor/camera/dist/esm/definitions.d.ts:1:38 - error TS1005: ';' expected.
> 
> 1 import type { PermissionState } from '@capacitor/core';
>                                        ~~~~~~~~~~~~~~~~~
> ../node_modules/@capacitor/camera/dist/esm/index.d.ts:1:13 - error TS1005: '=' expected.
> 
> 1 import type { CameraPlugin } from './definitions';
>               ~
> ../node_modules/@capacitor/camera/dist/esm/index.d.ts:1:35 - error TS1005: ';' expected.
> 
> 1 import type { CameraPlugin } from './definitions';
>                                     ~~~~~~~~~~~~~~~
> ../node_modules/@capacitor/device/dist/esm/index.d.ts:1:13 - error TS1005: '=' expected.
> 
> 1 import type { DevicePlugin } from './definitions';
>               ~
> ../node_modules/@capacitor/device/dist/esm/index.d.ts:1:35 - error TS1005: ';' expected.
> 
> 1 import type { DevicePlugin } from './definitions';
>                                     ~~~~~~~~~~~~~~~
> ```
> 
> my package.json file
> 
> ```
>  "dependencies": {
>         "@agm/core": "^1.0.0-beta.7",
>         "@angular/animations": "^8.2.1",
>         "@angular/cdk": "^8.2.1",
>         "@angular/common": "^8.2.1",
>         "@angular/compiler": "^8.2.1",
>         "@angular/core": "^8.2.1",
>         "@angular/forms": "^8.2.1",
>         "@angular/material": "^8.1.2",
>         "@angular/material-moment-adapter": "^8.1.2",
>         "@angular/platform-browser": "^8.2.1",
>         "@angular/platform-browser-dynamic": "^8.2.1",
>         "@angular/router": "^8.2.1",
>         "@capacitor/camera": "^1.0.2",
>         "@capacitor/cli": "^3.0.2",
>         "@capacitor/core": "^3.0.2",
>         "@capacitor/device": "^1.0.2",
>         "ng2-charts": "2.3.0",
>         "ngx-bootstrap": "^4.3.0",
>         "ngx-color-picker": "^8.2.0",
>         "ngx-device-detector": "^2.0.10",
>         "ngx-ellipsis": "^2.1.2",
>         "ngx-infinite-scroll": "^7.2.0",
>         "ngx-mapbox-gl": "^4.5.0",
>         "ngx-mat-select-search": "1.8.0",
>         "ngx-material-timepicker": "^4.0.2",
>         "quill": "^1.3.7",
>         "rxjs": "~6.4.0",
>         "tslib": "^1.9.0",
>         "underscore": "^1.9.2",
>         "uuid": "^8.3.2",
>         "uuid-generator-ts": "^1.0.3",
>         "web-animations-js": "^2.3.2",
>         "workbox-cli": "^5.1.4",
>         "xlsx": "^0.15.4",
>         "zone.js": "~0.9.1"
>     },
>     "devDependencies": {
>         "@angular-builders/custom-webpack": "8.4.1",
>         "@angular-devkit/build-angular": "^0.803.21",
>         "@angular/cli": "^8.3.21",
>         "@angular/compiler-cli": "^8.2.1",
>         "@angular/language-service": "^8.2.1",
>         "@babel/core": "^7.7.7",
>         "@types/bootstrap": "^4.3.1",
>         "@types/jasmine": "^3.4.0",
>         "@types/jasminewd2": "~2.0.3",
>         "@types/lodash-es": "^4.17.3",
>         "@types/mapbox-gl": "^1.9.1",
>         "@types/node": "^8.9.5",
>         "@types/uuid": "^8.3.0",
>         "@typescript-eslint/eslint-plugin": "^2.19.0",
>         "@typescript-eslint/eslint-plugin-tslint": "^2.19.0",
>         "@typescript-eslint/parser": "^2.19.0",
>         "babel-loader": "^8.0.6",
>         "codelyzer": "^5.2.1",
>         "eslint": "^6.8.0",
>         "eslint-config-airbnb-angular": "^1.0.0",
>         "eslint-config-prettier": "^6.10.0",
>         "eslint-plugin-import": "^2.20.1",
>         "eslint-plugin-prettier": "^3.1.2",
>         "jasmine-core": "~3.4.0",
>         "jasmine-spec-reporter": "~4.2.1",
>         "karma": "~4.1.0",
>         "karma-chrome-launcher": "~2.2.0",
>         "karma-coverage-istanbul-reporter": "^2.1.0",
>         "karma-jasmine": "~2.0.1",
>         "karma-jasmine-html-reporter": "^1.5.1",
>         "lint-staged": "^10.0.7",
>         "prettier": "^1.19.1",
>         "pretty-quick": "^2.0.1",
>         "ts-node": "~7.0.0",
>         "tslint": "~5.15.0",
>         "typescript": "~3.4.3"
>     },
>     "lint-staged": {
>         "*.ts": [
>             "eslint"
>         ]
>     }
> ```

Same issue with me. Do you happen to fix this? I'm having the same dependency as yours.

**Comment by phoenix503** [comment]
The solution to this is upgrade your typescript version 3.8+.
It will fix your issue or use Capacitor v2.
Both will resolve it.
Ref: [https://capacitorjs.com/docs/updating/3-0](url)
